# Generated by Django 3.1.5 on 2021-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeansMusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='commentCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='likeCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='shareCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
