# Generated by Django 3.2.6 on 2021-09-02 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知组', max_length=50, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='PPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='TTel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed_time', models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间')),
                ('name', models.CharField(default='未知账号', max_length=50, verbose_name='账号归属')),
                ('username', models.CharField(max_length=40, verbose_name='用户名')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站地址')),
                ('Introduce', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图标')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.eemail', verbose_name='关联邮箱')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.group', verbose_name='所属账号组')),
                ('password', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.ppassword', verbose_name='密码')),
                ('tel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.ttel', verbose_name='绑定的手机号')),
            ],
            options={
                'ordering': ['-last_changed_time'],
                'abstract': False,
            },
        ),
    ]
