# Generated by Django 3.1.6 on 2021-02-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed_time', models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间')),
                ('name', models.CharField(default='未知账号', max_length=50, verbose_name='账号归属')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站地址')),
                ('Introduce', models.TextField(blank=True, null=True, verbose_name='说明')),
            ],
            options={
                'ordering': ['-last_changed_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='TTel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
