# Generated by Django 3.1.6 on 2021-02-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.eemail', verbose_name='关联邮箱'),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.ppassword', verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='account',
            name='tel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.ttel', verbose_name='绑定的手机号'),
        ),
    ]
