# Generated by Django 3.1.5 on 2021-01-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Introduce',
            field=models.TextField(blank=True, null=True, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='关联邮箱'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='未知账号', max_length=50, verbose_name='账号归属'),
        ),
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='网站地址'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountSystem.password', verbose_name='密码'),
        ),
    ]
