# Generated by Django 3.2.6 on 2021-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知类型', max_length=50, verbose_name='名称')),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
    ]
