# Generated by Django 3.2.6 on 2021-09-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0002_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.accounttype', verbose_name='类型'),
        ),
    ]
