# Generated by Django 3.1.5 on 2021-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0002_auto_20210131_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=20, unique=True, verbose_name='密码'),
        ),
    ]
