# Generated by Django 3.1.6 on 2021-02-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0002_auto_20210213_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eemail',
            old_name='email',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='ttel',
            old_name='tel',
            new_name='content',
        ),
    ]
