# Generated by Django 3.1.6 on 2021-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0003_auto_20210213_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='未知账号', max_length=100, verbose_name='账号归属'),
        ),
    ]
