# Generated by Django 3.2.7 on 2021-09-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0005_auto_20210908_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.accounttype', verbose_name='类型'),
        ),
    ]
