# Generated by Django 3.1.6 on 2021-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0005_auto_20210422_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=40, verbose_name='用户名'),
        ),
    ]
