# Generated by Django 3.2.7 on 2021-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0006_alter_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppassword',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_changed_time',
        ),
        migrations.AddField(
            model_name='account',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='account',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='account',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='ppassword',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='ppassword',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='ppassword',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='ttel',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
