# Generated by Django 3.2.7 on 2021-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0007_auto_20210925_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eemail',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='ttel',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AddField(
            model_name='accounttype',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='eemail',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='eemail',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='eemail',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='group',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='group',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='group',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='ttel',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='ttel',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='ttel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
    ]
