# Generated by Django 3.2.7 on 2021-09-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0008_auto_20210925_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='eemail',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
