# Generated by Django 3.2.7 on 2021-09-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0009_eemail_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eemail',
            options={'verbose_name': '电子邮箱', 'verbose_name_plural': '所有电子邮箱'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '账号集', 'verbose_name_plural': '所有账号集'},
        ),
        migrations.AlterModelOptions(
            name='ppassword',
            options={'verbose_name': '密码', 'verbose_name_plural': '所有密码'},
        ),
        migrations.AlterModelOptions(
            name='ttel',
            options={'verbose_name': '手机号', 'verbose_name_plural': '所有手机号'},
        ),
    ]
