# Generated by Django 3.2.7 on 2021-10-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0010_auto_20210925_2233'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
