# Generated by Django 3.2.7 on 2021-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0012_rename_introduce_account_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tels',
            field=models.ManyToManyField(blank=True, related_name='tels', to='accountSystem.TTel', verbose_name='所有绑定的手机号'),
        ),
    ]
