# Generated by Django 3.2.7 on 2021-10-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0013_account_tels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TTel',
            new_name='Tel',
        ),
    ]
