# Generated by Django 3.2.7 on 2021-10-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0014_rename_ttel_tel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EEmail',
            new_name='Email',
        ),
    ]
