# Generated by Django 3.2.7 on 2021-10-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0015_rename_eemail_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PPassword',
            new_name='Password',
        ),
    ]
