# Generated by Django 3.2.7 on 2021-10-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0016_rename_ppassword_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='password',
            table='password',
        ),
    ]
