# Generated by Django 3.2.7 on 2021-10-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0017_alter_password_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='password',
            table=None,
        ),
    ]
