# Generated by Django 3.2.7 on 2021-10-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0019_alter_account_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounttype',
            table=None,
        ),
    ]
