# Generated by Django 3.2.7 on 2021-10-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0020_alter_accounttype_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountType',
            new_name='Type',
        ),
    ]
