# Generated by Django 3.2.7 on 2021-10-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0021_rename_accounttype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='emails', to='accountSystem.Email', verbose_name='所有绑定的电子邮箱'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.email', verbose_name='关联电子邮箱'),
        ),
    ]
