# Generated by Django 3.2.7 on 2021-10-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0022_auto_20211006_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tel',
        ),
    ]
