# Generated by Django 3.2.7 on 2021-12-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0023_auto_20211006_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=36, unique=True, verbose_name='密码'),
        ),
    ]
