# Generated by Django 4.0 on 2021-12-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0024_alter_password_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='typeBeta',
            field=models.ManyToManyField(related_name='accountTypes', to='accountSystem.Type'),
        ),
    ]
