# Generated by Django 4.0 on 2021-12-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0027_remove_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='types',
            field=models.ManyToManyField(related_name='accountTypes', to='accountSystem.Type', verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(editable=False, null=True, verbose_name='被删除时间')),
                ('wx_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nickName', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.group', verbose_name='所属账号组')),
                ('password', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.password', verbose_name='密码')),
                ('tel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.tel', verbose_name='绑定的手机号')),
            ],
            options={
                'verbose_name': '微信',
                'verbose_name_plural': '所有微信',
            },
        ),
    ]
