# Generated by Django 4.0 on 2021-12-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0028_alter_account_types_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wechat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.wechat', verbose_name='绑定的微信'),
        ),
    ]
