# Generated by Django 4.0 on 2021-12-28 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0029_account_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='未知类型', max_length=50, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.password', verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
