# Generated by Django 4.0 on 2022-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0030_alter_email_remark_alter_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(editable=False, null=True, verbose_name='被删除时间')),
                ('ip', models.GenericIPAddressField()),
                ('rootPwd', models.CharField(max_length=32, verbose_name='root账号密码')),
                ('remark', models.SlugField()),
                ('test2', models.JSONField()),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '所有服务器',
            },
        ),
    ]
