# Generated by Django 4.0 on 2022-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0031_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='test2',
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
