# Generated by Django 4.0 on 2022-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0035_alter_server_ip_serveruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruser',
            name='hasRootPriority',
            field=models.BooleanField(blank=True, default=False, verbose_name='拥有root权限'),
        ),
    ]
