# Generated by Django 4.0 on 2022-01-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0037_serveruser_owner_serveruser_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '个体/组织', 'verbose_name_plural': '所有个体/组织'},
        ),
        migrations.AlterModelOptions(
            name='serveruser',
            options={'verbose_name': '服务器用户', 'verbose_name_plural': '所有服务器用户'},
        ),
        migrations.AddField(
            model_name='server',
            name='hoster',
            field=models.PositiveSmallIntegerField(choices=[(1, '阿里云'), (2, '腾讯云'), (3, '哈密市希望科技有限公司')], null=True, verbose_name='托管方'),
        ),
        migrations.AlterField(
            model_name='server',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.group', verbose_name='所属个体/组织'),
        ),
    ]
