# Generated by Django 4.0 on 2022-01-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0038_alter_group_options_alter_serveruser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'tong y账号', 'verbose_name_plural': '所有tong y账号'},
        ),
        migrations.CreateModel(
            name='BT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(editable=False, null=True, verbose_name='被删除时间')),
                ('port', models.PositiveIntegerField(default=8888, verbose_name='端口')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('basicAuthUsername', models.CharField(max_length=32, null=True, verbose_name='BasicAuth用户名')),
                ('basicAuthPassword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basicAuthPassword', to='accountSystem.password', verbose_name='BasicAuth密码')),
                ('password', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.password', verbose_name='密码')),
                ('server', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.server', verbose_name='宿机')),
            ],
            options={
                'ordering': ['-updatedAt'],
                'abstract': False,
            },
        ),
    ]
