# Generated by Django 4.0 on 2022-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0041_alter_bt_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='面板路径'),
        ),
    ]
