# Generated by Django 4.0 on 2022-01-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0042_alter_bt_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(editable=False, null=True, verbose_name='被删除时间')),
                ('port', models.PositiveIntegerField(default=8888, verbose_name='端口')),
                ('rootPwd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.password', verbose_name='密码')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.server', verbose_name='服务器')),
            ],
            options={
                'ordering': ['-updatedAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbServerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(editable=False, null=True, verbose_name='被删除时间')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('hasRootPriority', models.BooleanField(blank=True, default=False, verbose_name='拥有root权限')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.group', verbose_name='所属个体/组织')),
                ('password', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.password', verbose_name='密码')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.dbserver', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '数据库用户',
                'verbose_name_plural': '所有数据库用户',
            },
        ),
    ]
