# Generated by Django 4.0 on 2022-01-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0043_dbserver_dbserveruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbserver',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
