# Generated by Django 4.0 on 2022-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0044_dbserver_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbserver',
            options={'verbose_name': '数据服务器', 'verbose_name_plural': '所有数据服务器'},
        ),
        migrations.AddField(
            model_name='bt',
            name='domain',
            field=models.URLField(blank=True, null=True, verbose_name='绑定的域名'),
        ),
    ]
