# Generated by Django 4.0 on 2022-01-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0045_alter_dbserver_options_bt_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.group', verbose_name='所属个体/组织'),
        ),
    ]
