# Generated by Django 4.0 on 2022-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0046_tel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hoster',
            field=models.PositiveSmallIntegerField(choices=[(1, '阿里云'), (2, '腾讯云'), (3, '哈密市希望科技有限公司'), (4, '新疆丝路融创网络科技有限公司（局域网）')], null=True, verbose_name='托管方'),
        ),
    ]
