# Generated by Django 4.0 on 2022-02-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0049_alter_wechat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechat',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.email', verbose_name='绑定的邮箱'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='微信号（ID）'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='nickName',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
