# Generated by Django 4.0 on 2022-02-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0050_wechat_email_alter_wechat_id_alter_wechat_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '通用账号', 'verbose_name_plural': '所有通用账号'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='icon',
        ),
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='type',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='网站地址'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='email',
            field=models.OneToOneField(blank=True, help_text='你可以使用一验证过的邮箱地址登陆微信，也可以用它来找回微信密码', null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.email', verbose_name='绑定的邮箱'),
        ),
    ]
