# Generated by Django 4.0 on 2022-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0051_alter_account_options_remove_account_icon_type_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='账号归属'),
        ),
    ]
