# Generated by Django 4.0 on 2022-02-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0053_alter_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='accountSystem.type', verbose_name='所属平台'),
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.group', verbose_name='所属个体/组织'),
        ),
    ]
