# Generated by Django 4.0 on 2022-02-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0054_account_platform_alter_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='accountTypes', to='accountSystem.Type', verbose_name='类型'),
        ),
    ]
