# Generated by Django 4.0 on 2022-02-04 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0055_alter_account_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(limit_choices_to={'url': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='accountSystem.type', verbose_name='所属平台'),
        ),
    ]
