# Generated by Django 4.0 on 2022-02-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0058_alter_account_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='types',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('url__isnull', True)), related_name='accountTypes', to='accountSystem.Type', verbose_name='类型'),
        ),
    ]
