# Generated by Django 4.0 on 2022-02-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0059_alter_account_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wechat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountSystem.wechat', verbose_name='绑定的微信'),
        ),
    ]
