# Generated by Django 4.0 on 2022-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0060_alter_account_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=36, verbose_name='密码'),
        ),
    ]
