# Generated by Django 4.0 on 2022-02-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0062_elasticsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticsearch',
            name='apmPwd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apm', to='accountSystem.password', verbose_name='apm_system'),
        ),
        migrations.AddField(
            model_name='elasticsearch',
            name='beatsPwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='accountSystem.password', verbose_name='beats_system'),
        ),
        migrations.AddField(
            model_name='elasticsearch',
            name='kibanaPwd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kibana', to='accountSystem.password', verbose_name='kibana_system'),
        ),
        migrations.AddField(
            model_name='elasticsearch',
            name='logstashPwd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logstash', to='accountSystem.password', verbose_name='logstash_system'),
        ),
        migrations.AddField(
            model_name='elasticsearch',
            name='remoteMonitoringPwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm', to='accountSystem.password', verbose_name='remote_monitoring_user'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='elasticPwd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='es', to='accountSystem.password', verbose_name='elastic'),
        ),
    ]
