# Generated by Django 4.0 on 2022-02-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0063_elasticsearch_apmpwd_elasticsearch_beatspwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticsearch',
            name='apmPwd',
            field=models.CharField(max_length=36, null=True, verbose_name='apm_system'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='beatsPwd',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='beats_system'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='elasticPwd',
            field=models.CharField(max_length=36, null=True, verbose_name='elastic'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='kibanaPwd',
            field=models.CharField(max_length=36, null=True, verbose_name='kibana_system'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='logstashPwd',
            field=models.CharField(max_length=36, null=True, verbose_name='logstash_system'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='remoteMonitoringPwd',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='remote_monitoring_user'),
        ),
    ]
