# Generated by Django 4.0 on 2022-03-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0064_alter_elasticsearch_apmpwd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbserver',
            name='rootPwd',
        ),
        migrations.AddField(
            model_name='dbserver',
            name='pwd',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='root密码'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='apmPwd',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='apm_system'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='kibanaPwd',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='kibana_system'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='logstashPwd',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='logstash_system'),
        ),
    ]
