# Generated by Django 4.0 on 2022-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0066_rename_dbserver_dbservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserveruser',
            name='password',
            field=models.CharField(max_length=32, null=True, verbose_name='密码'),
        ),
    ]
