# Generated by Django 4.0 on 2022-03-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0068_rename_dbserveruser_dbserviceuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbservice',
            options={'verbose_name': '数据服务', 'verbose_name_plural': '所有数据服务'},
        ),
    ]
