# Generated by Django 4.0 on 2022-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0069_alter_dbservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbservice',
            name='ttype',
            field=models.IntegerField(choices=[(0, 'MySQL'), (1, 'PostgreSQL')], default=0, verbose_name='数据库类型'),
        ),
    ]
