# Generated by Django 4.0 on 2022-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0070_dbservice_ttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='account',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='port',
            field=models.PositiveIntegerField(db_index=True, default=8888, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='remark',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='ttype',
            field=models.IntegerField(choices=[(0, 'MySQL'), (1, 'PostgreSQL')], db_index=True, default=0, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='dbserviceuser',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dbserviceuser',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='dbserviceuser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='port',
            field=models.PositiveIntegerField(db_index=True, default=8888, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='remark',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='email',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='email',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='email',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='password',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='password',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='password',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='type',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='type',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='type',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='deletedAt',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间'),
        ),
    ]
