# Generated by Django 2.2 on 2020-09-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影标题')),
                ('content', models.FileField(upload_to='', verbose_name='视频')),
            ],
        ),
    ]
