# Generated by Django 3.2.6 on 2021-09-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=400, verbose_name='临时访问链接'),
        ),
    ]
