# Generated by Django 2.2 on 2020-09-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('miniProgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='content',
            field=models.FileField(upload_to='video/', verbose_name='视频'),
        ),
    ]
