# Generated by Django 2.2 on 2020-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('miniProgram', '0002_auto_20200906_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='cover',
            field=models.ImageField(default='kino_cover/default.png', upload_to='kino_cover', verbose_name='电影封面'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='content',
            field=models.FileField(upload_to='video/', verbose_name='电影视频'),
        ),
    ]
