# Generated by Django 3.2.6 on 2021-09-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0002_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
