# Generated by Django 3.1.6 on 2021-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0002_auto_20210211_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='host',
            field=models.URLField(blank=True, null=True, verbose_name='服务器运行的地址'),
        ),
    ]
