# Generated by Django 2.2 on 2020-09-06 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('miniProgram', '0003_auto_20200906_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='每一集的名字')),
                ('content', models.FileField(upload_to='kino/', verbose_name='每一集的视频')),
            ],
        ),
        migrations.RemoveField(
            model_name='kino',
            name='content',
        ),
        migrations.AddField(
            model_name='kino',
            name='episodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='miniProgram.episode',
                                    verbose_name='集'),
        ),
    ]
