# Generated by Django 2.2 on 2020-09-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('miniProgram', '0004_auto_20200907_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kino',
            name='episodes',
        ),
        migrations.AddField(
            model_name='kino',
            name='episodes',
            field=models.ManyToManyField(to='miniProgram.episode'),
        ),
    ]
