# Generated by Django 3.1.6 on 2021-04-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0004_auto_20210214_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='miniProgram.image'),
        ),
    ]
