# Generated by Django 3.2.6 on 2021-09-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0004_auto_20210902_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='nameChinese',
            new_name='name_chinese',
        ),
    ]
