# Generated by Django 3.2.6 on 2021-09-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0005_rename_namechinese_film_name_chinese'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
