# Generated by Django 2.2 on 2020-09-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('miniProgram', '0005_auto_20200907_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kino',
            name='episodes',
        ),
        migrations.AddField(
            model_name='episode',
            name='kino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='miniProgram.kino'),
        ),
    ]
