# Generated by Django 3.2.6 on 2021-09-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0006_auto_20210902_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
    ]
