# Generated by Django 3.2.5 on 2021-08-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0006_subscriptionaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionaccount',
            options={'verbose_name': '微信订阅号', 'verbose_name_plural': '微信订阅号'},
        ),
    ]
