# Generated by Django 3.2.6 on 2021-09-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0007_auto_20210902_1807'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmtype',
            table='film_type',
        ),
    ]
