# Generated by Django 3.2.6 on 2021-09-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0009_video_is_hot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
