# Generated by Django 3.2.6 on 2021-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0011_rename_belongto_video_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='episodeNum',
            new_name='episode_num',
        ),
    ]
