# Generated by Django 3.2.7 on 2021-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0013_auto_20210908_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houselayout',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='houseprice',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='housepricetype',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='housesize',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='housesizeunit',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='redirecturlrelation',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='staticfiles',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='subcribtions',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='film',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='filmtype',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='house',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='houselayout',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='houseprice',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='housepricetype',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='housesize',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='housesizeunit',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='image',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='language',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='redirecturlrelation',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='staticfiles',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='subcribtions',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='subscriptionaccount',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='text',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='video',
            name='last_changed_time',
        ),
        migrations.AddField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='country',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='country',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='country',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='film',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='film',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='film',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='filmtype',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='filmtype',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='filmtype',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='house',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='house',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='house',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='houselayout',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='houselayout',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='houselayout',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='housepricetype',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='housepricetype',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='housepricetype',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='housesize',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='housesize',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='housesize',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='housesizeunit',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='housesizeunit',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='housesizeunit',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='language',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='language',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='language',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='redirecturlrelation',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='redirecturlrelation',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='redirecturlrelation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='settings',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='settings',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='settings',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='staticfiles',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='staticfiles',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='staticfiles',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='subcribtions',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='subcribtions',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='subcribtions',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='subscriptionaccount',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='text',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='text',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='text',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='video',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='video',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='video',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
    ]
