# Generated by Django 3.2.7 on 2021-09-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0014_auto_20210925_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='episode_num',
            new_name='episodeNum',
        ),
    ]
