# Generated by Django 3.2.7 on 2021-10-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0015_rename_episode_num_video_episodenum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '订阅号文章', 'verbose_name_plural': '所有订阅号文章'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家', 'verbose_name_plural': '所有国家'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': '所有Film'},
        ),
        migrations.AlterModelOptions(
            name='filmtype',
            options={'verbose_name': 'Film类别', 'verbose_name_plural': '所有Film类别'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '图片', 'verbose_name_plural': '所有图片'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': '语言', 'verbose_name_plural': '所有语言'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login_time'], 'verbose_name': '小程序用户', 'verbose_name_plural': '所有小程序用户'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '所有视频'},
        ),
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
        migrations.AlterModelTable(
            name='film',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filmtype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='language',
            table=None,
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
