# Generated by Django 3.2.7 on 2021-10-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0016_auto_20211007_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseprice',
            name='priceType',
        ),
        migrations.RemoveField(
            model_name='housesize',
            name='unit',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='HouseLayout',
        ),
        migrations.DeleteModel(
            name='HousePrice',
        ),
        migrations.DeleteModel(
            name='HousePriceType',
        ),
        migrations.DeleteModel(
            name='HouseSize',
        ),
        migrations.DeleteModel(
            name='HouseSizeUnit',
        ),
        migrations.DeleteModel(
            name='HouseType',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
