# Generated by Django 3.2.7 on 2021-10-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProgram', '0017_auto_20211007_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='show_times',
            new_name='showTimes',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name_chinese',
            new_name='nameChinese',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='show_times',
            new_name='showTimes',
        ),
        migrations.RenameField(
            model_name='filmtype',
            old_name='show_times',
            new_name='showTimes',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='file_name',
            new_name='fileName',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='media_id',
            new_name='mediaId',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='original_url',
            new_name='originalUrl',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='is_hot',
            new_name='isHot',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='show_times',
            new_name='showTimes',
        ),
    ]
