# Generated by Django 3.2.7 on 2021-09-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('ddl', models.DateTimeField(verbose_name='还款时间')),
                ('principle', models.FloatField(verbose_name='本金')),
                ('interest', models.FloatField(verbose_name='利息')),
                ('whose', models.CharField(max_length=100, verbose_name='所属')),
            ],
        ),
    ]
