# Generated by Django 3.2.7 on 2021-09-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtManagerSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_off',
            field=models.BooleanField(default=False, verbose_name='已还清'),
        ),
    ]
