# Generated by Django 3.2.7 on 2021-09-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DebtManagerSystem', '0002_debt_paid_off'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': '债务', 'verbose_name_plural': '所有债务'},
        ),
        migrations.AlterModelTable(
            name='debt',
            table='debt',
        ),
    ]
