# Generated by Django 3.2.7 on 2021-09-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtManagerSystem', '0003_auto_20210908_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='created_at',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='ddl',
            field=models.DateField(verbose_name='还款时间'),
        ),
    ]
