# Generated by Django 3.2.7 on 2021-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtManagerSystem', '0004_auto_20210908_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='debt',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='debt',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
    ]
