# Generated by Django 3.2.7 on 2021-10-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DebtManagerSystem', '0005_auto_20210925_1527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='debt',
            table=None,
        ),
    ]
