# Generated by Django 3.1.5 on 2021-01-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miniProgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed_time', models.DateTimeField(auto_now=True, verbose_name='最近一次修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='贴图名称')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='miniProgram.image')),
            ],
            options={
                'ordering': ['-last_changed_time'],
                'abstract': False,
            },
        ),
    ]
