# Generated by Django 3.2.7 on 2021-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB3DA', '0002_alter_map_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-updatedAt']},
        ),
        migrations.RemoveField(
            model_name='map',
            name='last_changed_time',
        ),
        migrations.AddField(
            model_name='map',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='map',
            name='deletedAt',
            field=models.DateTimeField(editable=False, null=True, verbose_name='被删除时间'),
        ),
        migrations.AddField(
            model_name='map',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近更新时间'),
        ),
    ]
