# Generated by Django 3.2.7 on 2021-10-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HousingTransactionSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='show_times',
            new_name='showTimes',
        ),
    ]
